services:
  app:
    image: "ghcr.io/vivite-project/cv-website:main"
    container_name: "cv-website"
    restart: always
    environment:
      - ENV_VARIABLE=production_server_only_variable
      - NEXT_PUBLIC_ENV_VARIABLE=production_public_variable
    ports:
      - 3002:3000
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    networks:
      - proxy

networks:
  proxy:
    external: true