services:
  cv-website:
    image: "ghcr.io/vivite-project/cv-website:main"
    restart: always
    env_file:
      - ".env.local"
    environment:
      - ENV_VARIABLE=production_server_only_variable
      - NEXT_PUBLIC_ENV_VARIABLE=production_public_variable
    deploy:
      mode: replicated
      replicas: 2
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    networks:
      - proxy

networks:
  proxy:
    external: true