services:
  cv-website:
    build: .
    restart: always
    env_file:
      - ".env.local"
    environment:
      - ENV_VARIABLE=production_server_only_variable
      - NEXT_PUBLIC_ENV_VARIABLE=production_public_variable
    deploy:
      mode: replicated
      replicas: 2
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    networks:
      - app

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: bd3443ba625c6dff251897af
    ports:
      - "27017:27017"
    volumes:
      - data:/data/db
    networks:
      - app

volumes:
  data:
    driver: local

networks:
  app:
    driver: bridge